---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/alertmanager
  - ../../../components/coreDns
  - ../../../components/kubeApiServer
  - ../../../components/kubeControllerManager
  - ../../../components/kubeEtcd
  - ../../../components/kubelet
  - ../../../components/kubeProxy
  - ../../../components/kubeScheduler
  - ../../../components/kubeStateMetrics
  - ../../../components/metrics-proxy
  - ../../../components/nodeExporter
  - ../../../components/prometheus
  - ../../../components/prometheusOperator
  - ../../../components/thanos

patchesStrategicMerge:
  - values.yaml
