---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/metrics
  - ../../../components/minio
  - ../../../components/node-agent
  # - ../../../components/schedule

patchesStrategicMerge:
  - values.yaml
