---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/bgp-control-plane
  - ../../../components/hubble
  - ../../../components/relay
  - ../../../components/ui
  - ../../../components/metrics

patchesStrategicMerge:
  - values.yaml
