---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:

  - target:
      kind: Ingress
      name: %NAME%
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: %NAME%.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: %NAME%.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: %NAME%-tls
      - op: replace
        path: /spec/rules/0/host
        value: %NAME%.k8s.example.com

  - target:
      kind: PersistentVolumeClaim
      name: %NAME%-config
    patch: |-
      - op: replace
        path: "/spec/storageClassName"
        value: truenas-iscsi-csi
      - op: replace
        path: "/spec/accessModes/0"
        value: ReadWriteOnce
      - op: replace
        path: "/spec/resources/requests/storage"
        value: 1Gi

  - target:
      kind: Deployment
      name: %NAME%
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: %NAME%
      spec:
        template:
          spec:
            containers:
              - name: %NAME%
                env:
                  - name: TZ
                    value: America/New_York
