---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-compact-statefulSet.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-compact-service.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-compact-serviceAccount.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-compact-serviceMonitor.yaml
