---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: private

resources:
  - ../../../helm

components:
  - ../../../components/ingress-class-resource
  - ../../../components/enable-ssl-passthrough
  - ../../../components/metrics

patchesStrategicMerge:
  - values.yaml
