---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: velero-chart
valuesInline:
  # Whether to deploy the node-agent daemonset.
  deployNodeAgent: true

  ## Default values

  # nodeAgent:
  #   podVolumePath: /var/lib/kubelet/pods
  #   # Pod priority class name to use for the node-agent daemonset. Optional.
  #   priorityClassName: ""
  #   # Resource requests/limits to specify for the node-agent daemonset deployment. Optional.
  #   # https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
  #   resources: {}
  #     # requests:
  #     #   cpu: 500m
  #     #   memory: 512Mi
  #     # limits:
  #     #   cpu: 1000m
  #     #   memory: 1024Mi

  #   # Tolerations to use for the node-agent daemonset. Optional.
  #   tolerations: []

  #   # Annotations to set for the node-agent daemonset. Optional.
  #   annotations: {}

  #   # labels to set for the node-agent daemonset. Optional.
  #   labels: {}

  #   # will map /scratch to emptyDir. Set to false and specify your own volume
  #   # via extraVolumes and extraVolumeMounts that maps to /scratch
  #   # if you don't want to use emptyDir.
  #   useScratchEmptyDir: true

  #   # Extra volumes for the node-agent daemonset. Optional.
  #   extraVolumes: []

  #   # Extra volumeMounts for the node-agent daemonset. Optional.
  #   extraVolumeMounts: []

  #   # Key/value pairs to be used as environment variables for the node-agent daemonset. Optional.
  #   extraEnvVars: {}

  #   # Additional command-line arguments that will be passed to the node-agent. Optional.
  #   # e.g.: extraArgs: ["--foo=bar"]
  #   extraArgs: []

  #   # Configure the dnsPolicy of the node-agent daemonset
  #   # See: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  #   dnsPolicy: ClusterFirst

  #   # SecurityContext to use for the Velero deployment. Optional.
  #   # Set fsGroup for `AWS IAM Roles for Service Accounts`
  #   # see more informations at: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
  #   podSecurityContext:
  #     runAsUser: 0
  #     # fsGroup: 1337

  #   # Container Level Security Context for the 'node-agent' container of the node-agent daemonset. Optional.
  #   # See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  #   containerSecurityContext: {}

  #   # Container Lifecycle Hooks to use for the node-agent daemonset. Optional.
  #   lifecycle: {}

  #   # Node selector to use for the node-agent daemonset. Optional.
  #   nodeSelector: {}

  #   # Affinity to use with node-agent daemonset. Optional.
  #   affinity: {}

  #   # DNS configuration to use for the node-agent daemonset. Optional.
  #   dnsConfig: {}

  #   # Update strategy to use for the node-agent daemonset. Optional.
  #   updateStrategy: {}
