---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - clusterissuer.yaml

secretGenerator:
  - name: cloudflare-api-token
    namespace: cert-manager
    envs:
      - api-token.env
    options:
      disableNameSuffixHash: true
      annotations:
        avp.kubernetes.io/path: "internal/data/k8s/common/cert-manager"
