---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: docker.io/cloudflare/cloudflared
    newTag: 2025.11.1

labels:
  - pairs:
      app.kubernetes.io/instance: cloudflared
      app.kubernetes.io/name: cloudflared
    includeTemplates: true
    includeSelectors: true
