---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: democratic-csi-chart
name: democratic-csi
repo: https://democratic-csi.github.io/charts
version: 0.15.0
releaseName: democratic-csi
namespace: democratic-csi
includeCRDs: true
valuesInline:
  controller:
    driver:
      image:
        registry: docker.io/democraticcsi/democratic-csi
        # renovate: image=docker.io/democraticcsi/democratic-csi
        tag: v1.9.3
        pullPolicy: IfNotPresent

    # https://kubernetes-csi.github.io/docs/external-attacher.html
    externalAttacher:
      enabled: true
      image:
        registry: registry.k8s.io/sig-storage/csi-attacher
        # renovate: image=registry.k8s.io/sig-storage/csi-attacher
        tag: v4.10.0
        pullPolicy: IfNotPresent

    # https://kubernetes-csi.github.io/docs/external-provisioner.html
    externalProvisioner:
      enabled: true
      image:
        # renovate: image=registry.k8s.io/sig-storage/csi-provisioner
        registry: registry.k8s.io/sig-storage/csi-provisioner
        # renovate: image=registry.k8s.io/sig-storage/csi-provisioner
        tag: v6.0.0
        pullPolicy: IfNotPresent

    # https://kubernetes-csi.github.io/docs/external-resizer.html
    externalResizer:
      enabled: true
      image:
        # renovate: image=registry.k8s.io/sig-storage/csi-resizer
        registry: registry.k8s.io/sig-storage/csi-resizer
        tag: v1.13.2
        pullPolicy: IfNotPresent

    # https://kubernetes-csi.github.io/docs/external-snapshotter.html
    externalSnapshotter:
      enabled: true
      # 1.20+ should use v4.0.0+
      # READ *before* updating from beta https://github.com/kubernetes-csi/external-snapshotter#usage
      image:
        # renovate: image=registry.k8s.io/sig-storage/csi-snapshotter
        registry: registry.k8s.io/sig-storage/csi-snapshotter
        tag: v8.2.1
        pullPolicy: IfNotPresent

    # https://github.com/kubernetes-csi/external-health-monitor
    externalHealthMonitorController:
      enabled: false
      image:
        # renovate: image=registry.k8s.io/sig-storage/csi-external-health-monitor-controller
        registry: registry.k8s.io/sig-storage/csi-external-health-monitor-controller
        tag: v0.14.0
        pullPolicy: IfNotPresent

  node:
    driver:
      image:
        # renovate: image=docker.io/democraticcsi/democratic-csi
        registry: docker.io/democraticcsi/democratic-csi
        tag: v1.9.3
        pullPolicy: IfNotPresent

    # https://kubernetes-csi.github.io/docs/node-driver-registrar.html
    driverRegistrar:
      enabled: true
      image:
        # renovate: image=registry.k8s.io/sig-storage/csi-node-driver-registrar
        registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.13.0
        pullPolicy: IfNotPresent

  # https://github.com/democratic-csi/csi-grpc-proxy
  csiProxy:
    enabled: true
    image:
        # renovate: image=docker.io/democraticcsi/csi-grpc-proxy
        registry: docker.io/democraticcsi/csi-grpc-proxy
        tag: v0.5.6
        pullPolicy: IfNotPresent
