---
apiVersion: v1
kind: Service
metadata:
  name: syslog-agent-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: syslog-agent.k8s.example.com
spec:
  ports:
    - port: 5140
      protocol: UDP
      targetPort: 5140
  selector:
    agent.k8s.elastic.co/name: syslog-agent
  type: LoadBalancer
