---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/tenant
  - ../../components/ingress

secretGenerator:
  - name: storage-user
    namespace: minio-tenant
    envs:
      - secrets/storage-user.env
    options:
      disableNameSuffixHash: true
      annotations:
        avp.kubernetes.io/path: "kv/data/kubernetes/workload-prod/minio"

  - name: storage-configuration
    namespace: minio-tenant
    files:
      - config.env=secrets/storage-configuration.env
    options:
      disableNameSuffixHash: true
      annotations:
        avp.kubernetes.io/path: "kv/data/kubernetes/workload-prod/minio"

patches:
  - path: tenant.patch.yaml
    target:
      kind: Tenant
    options:
      allowNameChange: true

  - target:
      kind: Ingress
      name: operator-console
      namespace: minio-operator
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: minio-operator-console.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: minio-operator-console.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: console-tls-ingress
      - op: replace
        path: "/spec/rules/0/host"
        value: minio-operator-console.k8s.example.com

  - target:
      kind: Ingress
      name: tenant-console
      namespace: minio-tenant
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: minio-tenant-console.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: minio-tenant-console.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: console-tls-ingress
      - op: replace
        path: "/spec/rules/0/host"
        value: minio-tenant-console.k8s.example.com

  - target:
      kind: Ingress
      name: tenant-api-https
      namespace: minio-tenant
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: buckets.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: buckets.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: api-tls-ingress
      - op: replace
        path: "/spec/rules/0/host"
        value: buckets.k8s.example.com

  - target:
      kind: Ingress
      name: tenant-api-http
      namespace: minio-tenant
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: buckets-http.k8s.example.com
