---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
   - ../../../components/vmsingle
   - ../../../components/alertmanager
   - ../../../components/vmalert
   - ../../../components/vmagent
   - ../../../components/prometheus-node-exporter
   - ../../../components/kube-state-metrics
   - ../../../components/kubelet
   - ../../../components/kubeApiServer
   - ../../../components/kubeControllerManager
   - ../../../components/coreDns
   - ../../../components/kubeEtcd
   - ../../../components/kubeScheduler
   - ../../../components/metrics-proxy
   - ../../../components/convert-prometheus-crds
   # - ../../../components/grafana-operator-dashboards
   - ../../../components/graphite-flags
   - ../../../components/prometheus-operator-crds

patchesStrategicMerge:
  - values.yaml
