---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/ingress-class-resource
  - ../../../components/enable-ssl-passthrough
  - ../../../components/metrics
  - ../../../components/use-forwarded-headers

patchesStrategicMerge:
  - values.yaml
