---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/storage-encryption
  - ../../../components/kubernetes-auth
  - ../../../components/default-vault-connection
  - ../../../components/metrics

patchesStrategicMerge:
  - values.yaml
