---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
  - ../../base

components:
  - ../../components/metrics
  - ../../components/dashboards
  - ../../components/plugin-barman-cloud

patches:
  - target:
      name: cnpg-controller-manager
      kind: Deployment
    patch: |-
      - op: remove
        path: "/spec/template/spec/containers/0/resources/limits"
