---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./helm

resources:
  - externalsecret.yaml
  
# components:
#   - ../../components/otel-k8s-daemonset
#   - ../../components/otel-k8s-deployment

configMapGenerator:
  - name: otel-config
    literals:
      - OTEL_COLLECTOR_ENDPOINT=http://clickstack-otel-collector:4318
    options:
      disableNameSuffixHash: true
