---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/freeipa-ca
  - ../../components/vault-k8s-ca
  - ../../components/vault-oci-ca
  - ../../components/ca-certificates-bundle
  - ../../components/ca-bundle

generators:
  - ./helm
