---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  -  ../../../components/otel-k8s-daemonset
  - ../../../components/otel-k8s-deployment

patchesStrategicMerge:
  - values.yaml
