---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/instance: mariadb
  app.kubernetes.io/name: mariadb

images:
  - name: mariadb
    newTag: 10.11.14

configMapGenerator:
  - name: mariadb-config
    files:
      - my.cnf

secretGenerator:
  - name: mariadb
    type: Opaque
    envs:
      - secrets/creds.env
