---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - daemonset.yaml

configMapGenerator:
  - name: vector-agent-config
    files:
      - agent.yaml

images:
  - name: docker.io/timberio/vector
    newTag: 0.51.1-debian

labels:
  - pairs:
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vector
      app.kubernetes.io/component: agent
    includeSelectors: true
    includeTemplates: true
