---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: freshrss
      app.kubernetes.io/name: freshrss
    includeSelectors: true
    includeTemplates: true

images:
  - name: freshrss/freshrss
    newTag: 1.27.1

replacements:
  - path: replacement.yaml
