---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

components:
  - ../../components/freeipa-acme-issuer
  - ../../components/vault-issuer
  - ../../components/letsencrypt-prod-issuer
  - ../../components/metrics

patches:
  - path: vault-issuer.patch.yaml
