---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - pvc.yaml

images:
  - name: redis
    newTag: 7.4.7

commonLabels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
