---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-router-deployment.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-router-service.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-router-serviceAccount.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-router-configmap.yaml
