---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - issuers.yaml
  - certificates.yaml
  - cnpg
  - externalsecret.yaml
  - pushsecret.yaml

generators:
  - ./helm
