---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ciliumbgp.yaml
  - ciliumloadbalancerippool.yaml

components:
  - ../../components/dashboards

generators:
  - ./helm
