---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cluster.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - externalsecret.yaml
  - pushsecret.yaml
  - secretstore.yaml

configurations:
  - transformers.yaml

images:
  - name: ghcr.io/cloudnative-pg/postgresql
    newTag: 17.5-1

labels:
  - pairs:
      app.kubernetes.io/name: cloudnativepg
      app.kubernetes.io/component: cloudnativepg
    includeTemplates: false
    includeSelectors: false
