---
apiVersion: v1
kind: Service
metadata:
  name: eventsource-webhook-gitea
spec:
  type: ClusterIP
  selector:
    eventsource-name: webhook
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
