---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: public

resources:
  - ../../../helm

components:
  - ../../../components/ingress-class-resource
  - ../../../components/metrics

patchesStrategicMerge:
  - values.yaml
