---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: longhorn-chart
name: longhorn
repo: https://charts.longhorn.io
version: 1.10.1
releaseName: longhorn
namespace: longhorn-system
includeCRDs: true
valuesInline:
  global:
    imageRegistry: "docker.io"
  preUpgradeChecker:
    jobEnabled: false
