---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  - https://github.com/argoproj/argo-workflows/manifests/namespace-install?ref=v3.7.6
  - ingress.yaml

images:
  - name: quay.io/argoproj/workflow-controller
    newTag: v3.7.6
  - name: quay.io/argoproj/argocli
    newTag: v3.7.6
  - name: quay.io/argoproj/argoexec
    newTag: v3.7.6
