---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: democratic-csi-chart
releaseName: truenas-iscsi-slow
valuesInline:
  csiDriver:
    # should be globally unique for a given cluster
    name: "org.ops-prod-democratic-csi.iscsi-slow"

  # add note here about volume expansion requirements
  storageClasses:
  - name: truenas-iscsi-slow-csi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: ext4

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"

    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
  #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
  #      # if doing CHAP
  #      node-db.node.session.auth.authmethod: CHAP
  #      node-db.node.session.auth.username: foo
  #      node-db.node.session.auth.password: bar
  #
  #      # if doing mutual CHAP
  #      node-db.node.session.auth.username_in: baz
  #      node-db.node.session.auth.password_in: bar
      node-publish-secret:
      controller-expand-secret:

  # if your cluster supports snapshots you may enable below
  volumeSnapshotClasses:
    - name: truenas-iscsi-slow
      parameters:
        # if true, snapshots will be created with zfs send/receive
        detachedSnapshots: "false"
      # secrets:
      #   snapshotter-secret:

  driver:
    existingConfigSecret: democratic-csi-driver-config-iscsi-slow
    config:
      # please see the most up-to-date example of the corresponding config here:
      # https://github.com/democratic-csi/democratic-csi/tree/master/examples
      # YOU MUST COPY THE DATA HERE INLINE!
      driver: freenas-api-iscsi
