---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: external-secrets-chart
name: external-secrets
repo: https://charts.external-secrets.io
version: 1.1.1
releaseName: external-secrets
namespace: external-secrets
includeCRDs: true
valuesInline:
  installCRDs: true
