---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauth2-proxy

generators:
  - ./helm

configMapGenerator:
  - name: oauth2-proxy-config
    files:
      - oauth2_proxy.cfg
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: oauth-client-secret
    envs:
      - secrets/client.txt
    options:
      disableNameSuffixHash: true
