---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ntfy

resources:
  - ../../base

components:
  - ../../components/smtp
  - ../../components/metrics

configMapGenerator:
  - name: ntfy-config
    files:
      - server.yml=ntfy-server.yml

patches:
  - target:
      kind: Ingress
      name: ntfy
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: ntfy.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: ntfy.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: ntfy-tls
      - op: replace
        path: /spec/rules/0/host
        value: ntfy.k8s.example.com

  - target:
      kind: PersistentVolumeClaim
      name: ntfy-data
    patch: |-
      - op: replace
        path: "/spec/storageClassName"
        value: truenas-iscsi-csi
      - op: replace
        path: "/spec/accessModes/0"
        value: ReadWriteOnce
      - op: replace
        path: "/spec/resources/requests/storage"
        value: 1Gi
