---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx-chart
name: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx
version: 4.14.1
releaseName: ingress-nginx
namespace: ingress-nginx
includeCRDs: false
valuesInline:
  controller:
    # -- This configuration defines if Ingress Controller should allow users to set
    # their own *-snippet annotations, otherwise this is forbidden / dropped
    # when users add those annotations.
    # Global snippets in ConfigMap are still respected
    allowSnippetAnnotations: true
    config:
      # Required to use server-snippet annotations as of controller-1.12/chart-4.12
      annotations-risk-level: Critical
