---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/instance: registry
  app.kubernetes.io/name: registry

images:
  - name: registry
    newTag: 3.0.0

configMapGenerator:
  - name: registry-config
    files:
      - config.yml=registry-config.yaml

secretGenerator:
  - name: registry-secret
    envs:
      - secrets/secret.env
