---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - bundle.yaml

secretGenerator:
  - name: vault-k8s-ca
    files:
      - ca.crt
    options:
      disableNameSuffixHash: true
