---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: solidnerd/bookstack
    newTag: 25.11.5

labels:
  - pairs:
      app.kubernetes.io/instance: bookstack
      app.kubernetes.io/name: bookstack
    includeSelectors: true
    includeTemplates: true
