---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb

resources:
  - ../../base


configMapGenerator:
  - name: mariadb-config
    behavior: replace
    files:
      - my.cnf

secretGenerator:
  - name: mariadb
    behavior: replace
    envs:
      - secrets/creds.env
    options:
      annotations:
        avp.kubernetes.io/path: "kv/data/kubernetes/workload-prod/mariadb"


patches:
  - target:
      kind: PersistentVolumeClaim
      name: mariadb-data
    patch: |-
      - op: replace
        path: "/spec/accessModes/0"
        value: ReadWriteOnce
      - op: replace
        path: "/spec/resources/requests/storage"
        value: 16Gi
      - op: add
        path: "/spec/storageClassName"
        value: truenas-iscsi-csi
