---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime-kuma

resources:
  - ../../base

components:
  - ../../components/custom-ca

patches:
  - target:
      kind: Ingress
      name: uptime-kuma
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: kuma.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: kuma.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: uptime-kuma-tls-ingress
      - op: replace
        path: /spec/rules/0/host
        value: kuma.k8s.example.com

  - target:
      kind: PersistentVolumeClaim
      name: uptime-kuma-config
    patch: |-
      - op: replace
        path: "/spec/storageClassName"
        value: truenas-iscsi-csi
      - op: replace
        path: "/spec/accessModes/0"
        value: ReadWriteOnce
      - op: replace
        path: "/spec/resources/requests/storage"
        value: 1Gi
