---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-ingestor-default-service.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-ingestor-statefulSet.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-ingestor-serviceAccount.yaml
  - https://raw.githubusercontent.com/thanos-io/kube-thanos/v0.29.0/examples/all/manifests/thanos-receive-ingestor-configmap.yaml
