---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vault-chart
name: vault
repo: https://helm.releases.hashicorp.com
version: 0.31.0
releaseName: vault
namespace: vault
includeCRDs: true
valuesInline:
  global:
    enabled: false
  injector:
    image:
      repository: "docker.io/hashicorp/vault-k8s"
      # renovate: image=docker.io/hashicorp/vault-k8s
      tag: "1.7.0"
    agentImage:
      repository: "docker.io/hashicorp/vault"
      # renovate: image=docker.io/hashicorp/vault
      tag: "1.21.1"
  server:
    image:
      repository: "docker.io/hashicorp/vault"
      # renovate: image=docker.io/hashicorp/vault
      tag: "1.21.1"
  csi:
    agent:
      image:
        repository: "docker.io/hashicorp/vault"
      # renovate: image=docker.io/hashicorp/vault
        tag: "1.21.1"
