---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  - https://github.com/argoproj/argo-events/manifests/namespace-install?ref=v1.9.9
  # - https://github.com/argoproj/argo-events/manifests/extensions/validating-webhook?ref=v1.8.0
  - sensor-rbac.yaml
  - workflow-rbac.yaml
  - eventbus.yaml

# configMapGenerator:
#   - name: argo-events-controller-config
#     behavior: replace
#     files:
#       - controller-config.yaml
#     options:
#       disableNameSuffixHash: true
