---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - deployment.yaml
  - ingress.yaml
  - rbac.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: netbox
      app.kubernetes.io/instance: netbox
      app.kubernetes.io/part-of: netbox
    includeSelectors: true
    includeTemplates: true

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.4.7

configMapGenerator:
  - name: netbox-config
    files:
      - configuration.py
      - netbox.yaml

replacements:
  - path: replacement.yaml
