---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vault-chart
valuesInline:
  injector:
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
      tag: "1.7.0-ubi"
    agentImage:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.20.3-ubi"
  server:
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.20.3-ubi"
  csi:
    agent:
      image:
        repository: "registry.connect.redhat.com/hashicorp/vault"
        tag: "1.20.3-ubi"
