---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - daemonset.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml

configMapGenerator:
  - name: metrics-proxy-config
    files:
      - haproxy.cfg

images:
  - name: docker.io/haproxy
    newTag: 3.3.0
