---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.20.0

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.20.0

patches:
  - target:
      name: external-dns
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/envFrom"
        value:
          - configMapRef:
              name: external-dns-config
          - secretRef:
              name: external-dns-secret
