---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

components:
  - ../../components/dashboard

patches:
  - target:
      kind: GrafanaDashboard
      name: argo-workflows
    patch: |-
      - op: replace
        path: "/spec/datasources/0/datasourceName"
        value: "VictoriaMetrics"
