---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/ingress
  - ../../../components/metrics

patchesStrategicMerge:
  - values.yaml
