---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: renovate

resources:
  - ../../base

configMapGenerator:
  - name: renovate-config
    behavior: replace
    files:
      - config.json

secretGenerator:
  - name: renovate-secret
    behavior: replace
    envs:
      - secrets/secret.env
    options:
      annotations:
        avp.kubernetes.io/path: "internal/data/k8s/ops-prod/renovate"

patches:
  - target:
      kind: PersistentVolumeClaim
      name: renovate-cache
    patch: |-
      - op: replace
        path: "/spec/storageClassName"
        value: truenas-nfs-csi
      - op: replace
        path: "/spec/accessModes/0"
        value: ReadWriteOnce
      - op: replace
        path: "/spec/resources/requests/storage"
        value: 1Gi
