---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/grafana/grafana-operator/releases/download/v5.20.0/kustomize-cluster_scoped.yaml
  - grafana.yaml

secretGenerator:
  - name: grafana-admin-creds
    envs:
      - secrets/grafana-admin-creds.env
    options:
      disableNameSuffixHash: true
