---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/remote-kubernetes-agent

secretGenerator:
  - name: elastic-agent-fleet-config
    envs:
      - secrets/fleet-config
    options:
      disableNameSuffixHash: true
