---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

components:
  - ../../../components/server-ha
  - ../../../components/injector
  - ../../../components/ui
  - ../../../components/tls
  - ../../../components/raft

patchesStrategicMerge:
  - values.yaml
