---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack

resources:
  - ../../base

components:
  - ../../components/ca-bundle

secretGenerator:
  - name: bookstack-env
    envs:
      - bookstack.env
    options:
      annotations:
        avp.kubernetes.io/path: "kv/data/kubernetes/workload-prod/bookstack"

patches:

  - target:
      kind: Ingress
      name: bookstack
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: bookstack.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: bookstack.k8s.example.com
      - op: replace
        path: /spec/rules/0/host
        value: bookstack.k8s.example.com
