---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
  - ../../base

configMapGenerator:
  - name: registry-config
    behavior: replace
    files:
      - config.yml=registry-config.yaml

secretGenerator:
  - name: registry-secret
    behavior: replace
    envs:
      - secrets/secret.env
    options:
      annotations:
        avp.kubernetes.io/path: "internal/data/k8s/ops-prod/registry"

patches:

  - target:
      kind: Ingress
      name: registry
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
      - op: add
        path: "/metadata/annotations/cert-manager.io~1common-name"
        value: docker-registry.k8s.example.com
      - op: replace
        path: "/spec/tls/0/hosts/0"
        value: docker-registry.k8s.example.com
      - op: replace
        path: "/spec/tls/0/secretName"
        value: registry-tls
      - op: replace
        path: /spec/rules/0/host
        value: docker-registry.k8s.example.com
