---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netbox

resources:
  - ../../base
  - valkey
  - cnpg
  - externalsecret.yaml
  - pushsecret.yaml

components:
  - ../../../../components/ca-bundle

configMapGenerator:
  - name: netbox-config
    behavior: merge
    files:
      - netbox.yaml

replacements:
  - sourceValue: "netbox.k8s.example.com"
    targets:
      - select:
          kind: Ingress
          name: netbox
        fieldPaths:
          - metadata.annotations.[cert-manager.io/common-name]
          - spec.tls.0.hosts.0
          - spec.rules.0.host
        options:
          create: true

patches:
  - target:
      kind: Ingress
      name: netbox
    patch: |-
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: vault-issuer
