---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin/overlays/nfd_labeled_nodes?ref=v0.34.1

images:
 - name: intel/intel-gpu-plugin
   newName: docker.io/intel/intel-gpu-plugin
