---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thanos

resources:
  - ../../base

components:
  - ../../components/thanos-query
#
patches:
  - target:
      name: thanos-query
      kind: Deployment
    path: query.yaml
  - target:
      name: thanos-query
      kind: Service
    patch: |-
      - op: add
        path: "/metadata/annotations/external-dns.alpha.kubernetes.io~1hostname"
        value: thanos-workload.k8s.example.com
      - op: replace
        path: "/spec/type"
        value: LoadBalancer
