---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kyverno-chart
valuesInline:
  admissionController:
    replicas: 3
  backgroundController:
    replicas: 2
  cleanupController:
    replicas: 2
  reportsController:
    replicas: 2
